version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - rusty-tub
  web:
    build: .
    env_file: .env.docker
    ports:
      - '8080:8080'
    networks:
      - rusty-tub
volumes:
  postgres-db:
    driver: local
networks:
  rusty-tub:
    driver: bridge